import { Icon, TagList } from './components'

type DetailData = {
  type: 'Project' | 'Experience'
  eyebrow: string
  title: string
  meta: string
  description: string
  tags: string[]
  image?: string
  repoLabel: string
}

const details: Record<string, DetailData> = {
  'retail-demand-forecasting': { type: 'Project', eyebrow: 'Featured project', title: 'Retail Demand Forecasting', meta: '2026 / In progress', description: 'A retail demand forecasting and inventory decision-support system built on the M5 Walmart dataset.', tags: ['Python', 'Forecasting', 'LightGBM'], image: '../placeholder-project-1.svg', repoLabel: 'View repository' },
  'roommate-expense-tracker': { type: 'Project', eyebrow: 'Product system', title: 'Roommate Expense Tracker', meta: '2025 / Prototype', description: 'A placeholder case study for a shared household expense product designed to make balances simple to understand and maintain.', tags: ['React', 'Flask', 'SQLite'], image: '../placeholder-project-2.svg', repoLabel: 'View repository' },
  'diabetes-prediction': { type: 'Project', eyebrow: 'Team project', title: 'Diabetes Classification', meta: '2026 / Completed study', description: 'A completed team analysis comparing seven model families on CDC BRFSS survey data, with Logistic Regression, XGBoost, and SHAP as Zach\'s primary contributions.', tags: ['R', 'XGBoost', 'SHAP'], image: '../diabetes-shap-summary.svg', repoLabel: 'View repository' },
  'ab-test-efficiency': { type: 'Project', eyebrow: 'Causal inference', title: 'A/B Test Efficiency', meta: '2026 / Completed study', description: 'A CUPED and regression-adjustment study using a real randomized email experiment and Monte Carlo simulation to evaluate more efficient experimentation.', tags: ['Python', 'CUPED', 'Causal inference'], image: '../ab-test-power-sample.png', repoLabel: 'View repository' },
  'airline-overbooking': { type: 'Project', eyebrow: 'Applied mathematics', title: 'Airline Overbooking Optimization', meta: '2025 / Completed study', description: 'A probabilistic modeling and Monte Carlo simulation study finding revenue-maximizing overbooking rates while accounting for compensation and customer-loyalty costs.', tags: ['Python', 'Monte Carlo', 'Optimization'], image: '../airline-overbooking-revenue.svg', repoLabel: 'View repository' },
  'data-analysis-eda': { type: 'Project', eyebrow: 'Analytics', title: 'Exploratory Data Analysis', meta: '2025 / Completed analyses', description: 'Two Python notebook analyses covering Superstore retail transactions and Premier League match data.', tags: ['Python', 'pandas', 'EDA'], image: '../premier-league-goals-rank.png', repoLabel: 'View repository' },
  dexcom: { type: 'Experience', eyebrow: 'Dexcom', title: 'Business Intelligence Intern', meta: '2024 — 2025', description: 'Worked with data and operations teams to turn business questions into clear analytical stories. This page is a placeholder for the projects, responsibilities, and outcomes from the internship.', tags: ['Business intelligence', 'Analytics', 'Data'], repoLabel: 'Back to portfolio' },
  'it-business-analyst': { type: 'Experience', eyebrow: 'Information Technology', title: 'IT Business Analyst Intern', meta: '2023 — 2024', description: 'Built a foundation in systems thinking, process improvement, and the human side of technical work. This page is a placeholder for the role details and selected work.', tags: ['Business analysis', 'Systems', 'Process'], repoLabel: 'Back to portfolio' },
}

function DiabetesClassificationPage() {
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell diabetes-page">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><a className="back-link" href={backHref}>← Back to portfolio</a></header>
      <main className="retail-dashboard section-wrap diabetes-dashboard">
        <header className="retail-dashboard-header"><div className="retail-dashboard-title"><div><h1>Diabetes Classification</h1><p>Led a 5-person team comparing seven model families on CDC BRFSS 2015 survey data, personally owning the Logistic Regression baseline, XGBoost pipeline, SHAP investigation, and repository delivery.</p></div><a className="diabetes-repo-button" href="https://github.com/ZachSkiba/CSP571-G7" target="_blank" rel="noreferrer">View on GitHub <Icon name="arrow" size={16} /></a></div><div className="retail-badge-container"><span className="retail-badge retail-badge-status"><i /> Completed project</span><span className="retail-badge">5-person team</span><span className="retail-badge">253,680 respondents</span><span className="retail-badge">Binary + multiclass</span></div></header>

        <section className="retail-metrics-grid" aria-label="Project metrics"><div className="retail-metric-card retail-metric-card--coral"><span>Best Binary ROC-AUC</span><strong>0.8325</strong><small>XGBoost · best of 7 model families</small></div><div className="retail-metric-card retail-metric-card--slate"><span>Best Binary F1</span><strong>0.4435</strong><small>Logistic Regression · team benchmark</small></div><div className="retail-metric-card retail-metric-card--sage"><span>Data Scale</span><strong>253,680</strong><small>Respondents · 21 survey features</small></div><div className="retail-metric-card"><span>Technical Ownership</span><strong>2 model families</strong><small>Logistic Regression + XGBoost</small></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Leadership &amp; Ownership</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>Led the project structure</h3><p>Set up the repository, authored and revised the shared project plan across four weeks, established the comparison workflow, and completed the final reorganization into a submission-ready structure.</p><div className="retail-callout"><strong>Delivery ownership</strong><p>23 of the team's 51 commits came from work spanning repository setup, EDA, modeling, documentation, and final delivery.</p></div></article><article className="retail-dashboard-card"><h3>Owned the core modeling work</h3><p>Built the team's Logistic Regression benchmark and absorbed the full XGBoost pipeline when project roles shifted, covering binary and multiclass targets, feature engineering, tuning, and interpretation.</p><div className="retail-callout retail-callout--sage"><strong>Team contribution</strong><p>Created a strong, interpretable baseline and a modern ensemble so the team could compare model complexity against actual lift.</p></div></article></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Technical Investigation</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>SHAP-driven model diagnosis</h3><p>Compared XGBoost SHAP rankings against Logistic Regression odds ratios to explain why the nonlinear model added almost no lift. The evidence showed the underlying decision boundary was close to linear.</p><div className="retail-callout"><strong>Explained the flat result</strong><p>Instead of treating the near-tie as a dead end, the analysis showed why extra model capacity was not producing new signal.</p></div></article><article className="retail-dashboard-card"><h3>Feature engineering with a falsifiable test</h3><p>Designed six SHAP-motivated interaction features, then ran a second SHAP pass after evaluation. The tree model was already learning those interactions implicitly.</p><div className="retail-callout retail-callout--sage"><strong>Engineering judgment</strong><p>Rejected added complexity when held-out metrics did not improve, preventing a more complicated model without additional information.</p></div></article></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Model Results</h2><div className="retail-table-wrap"><table className="retail-table"><thead><tr><th>Model / task</th><th>F1</th><th>ROC-AUC / accuracy</th><th>Key assessment</th></tr></thead><tbody><tr><td><strong>Logistic Regression · binary</strong></td><td>0.4435</td><td>0.8237 ROC-AUC</td><td>Best F1 in team comparison</td></tr><tr className="retail-table-highlight"><td><strong>XGBoost · binary</strong></td><td>0.4429</td><td><strong>0.8325 ROC-AUC</strong></td><td><strong>Best AUC in team comparison</strong></td></tr><tr><td><strong>XGBoost · multiclass</strong></td><td>0.440 macro</td><td>0.788 accuracy</td><td>Best overall multiclass metrics</td></tr><tr><td><strong>All models · prediabetes</strong></td><td>0.022–0.056</td><td>—</td><td>Clinical biomarker gap, not a model-selection win</td></tr></tbody></table></div><p className="retail-table-note">This is a completed analysis project, not a clinically deployable diagnostic system. The survey data does not include the clinical biomarkers needed to reliably identify prediabetes.</p></section>

        <section className="retail-dashboard-section diabetes-tech-section"><h2 className="retail-dashboard-section-title">Technology</h2><div className="retail-tech-stack"><TagList items={['R', 'Python', 'caret', 'glmnet', 'xgboost', 'SHAP Interpretability', 'pROC', 'ggplot2', 'Git', 'GitHub']} /></div><p className="retail-private-note">R was the primary modeling language; Python supported exploratory data analysis. SHAP was used to interpret the XGBoost model and compare its feature structure with Logistic Regression. The project used flat-file survey data with no deployment target.</p></section>
      </main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><span className="footer-year">© 2026</span></footer>
    </div>
  )
}

function ABTestEfficiencyPage() {
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell ab-test-page">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><a className="back-link" href={backHref}>← Back to portfolio</a></header>
      <main className="retail-dashboard section-wrap ab-test-dashboard">
        <header className="retail-dashboard-header"><div className="retail-dashboard-title"><div><h1>A/B Test Efficiency</h1><p>Built an end-to-end experimentation pipeline comparing a standard difference-in-means estimator against CUPED regression adjustment, then validated when variance reduction translates into higher power and fewer users.</p></div><a className="ab-test-repo-button" href="https://github.com/ZachSkiba/A-B-Test-Efficiency" target="_blank" rel="noreferrer">View on GitHub <Icon name="arrow" size={16} /></a></div><div className="retail-badge-container"><span className="retail-badge retail-badge-status"><i /> Completed project</span><span className="retail-badge">Solo project</span><span className="retail-badge">Real email experiment</span><span className="retail-badge">Simulation validated</span></div></header>

        <section className="retail-metrics-grid" aria-label="Project metrics"><div className="retail-metric-card retail-metric-card--coral"><span>Maximum Variance Reduction</span><strong>34.2%</strong><small>At covariate strength ρ = 0.6</small></div><div className="retail-metric-card retail-metric-card--slate"><span>Power Improvement</span><strong>+17.9 pp</strong><small>Same confidence, stronger covariate</small></div><div className="retail-metric-card retail-metric-card--sage"><span>Users Required</span><strong>−36%</strong><small>Approximate reduction at ρ = 0.6</small></div><div className="retail-metric-card"><span>Type I Error</span><strong>0.043–0.061</strong><small>Controlled around the 5% target</small></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Experiment Design &amp; Validation</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>Real randomized experiment</h3><p>Started with a 64,000-user Hillstrom email experiment and filtered it to a clean 42,613-user two-arm comparison. Calculated baseline rate, minimum detectable effect, sample size, and the standard treatment-effect estimate.</p><div className="retail-callout"><strong>Why it matters</strong><p>The real experiment anchors the analysis in an actual randomized trial instead of a purely synthetic example.</p></div></article><article className="retail-dashboard-card"><h3>Validated against theory and bootstrap</h3><p>Cross-validated closed-form OLS estimates and confidence intervals against 1,000 bootstrap resamples. The two inference approaches landed almost exactly on top of each other.</p><div className="retail-callout retail-callout--sage"><strong>Result</strong><p>Empirical variance reduction tracked the theoretical ρ² ceiling across the simulation grid.</p></div></article></div></section>

        <section className="retail-dashboard-section ab-test-evidence-section"><h2 className="retail-dashboard-section-title">Simulation Evidence</h2><p className="ab-test-evidence-note">CUPED preserves the causal estimate while its practical value depends on how predictive the pre-treatment covariate is.</p><div className="ab-test-visual"><img src="../ab-test-power-curves.png" alt="Power curves comparing unadjusted and CUPED-adjusted A/B test results across covariate strengths" /></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Technology</h2><div className="retail-tech-stack"><TagList items={['Python', 'NumPy', 'Pandas', 'SciPy', 'statsmodels', 'scikit-learn', 'Matplotlib', 'Seaborn', 'Jupyter']} /></div><p className="retail-private-note">A completed analysis project with a public repository and no deployed application. Future extensions include heterogeneous treatment effects and additional pre-treatment covariates.</p></section>
      </main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><span className="footer-year">© 2026</span></footer>
    </div>
  )
}

function AirlineOverbookingPage() {
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell airline-page">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><a className="back-link" href={backHref}>← Back to portfolio</a></header>
      <main className="retail-dashboard section-wrap airline-dashboard">
        <header className="retail-dashboard-header"><div className="retail-dashboard-title"><div><h1>Airline Overbooking Optimization</h1><p>Built a probabilistic modeling and Monte Carlo simulation pipeline to find the revenue-maximizing overbooking rate while accounting for no-shows, passenger compensation, and long-term customer loyalty.</p></div><a className="airline-repo-button" href="https://github.com/ZachSkiba/Airline-Overbooking" target="_blank" rel="noreferrer">View on GitHub <Icon name="arrow" size={16} /></a></div><div className="retail-badge-container"><span className="retail-badge retail-badge-status"><i /> Completed project</span><span className="retail-badge">2-person team</span><span className="retail-badge">Domestic + international</span><span className="retail-badge">Monte Carlo modeling</span></div></header>

        <section className="retail-metrics-grid" aria-label="Project metrics"><div className="retail-metric-card retail-metric-card--coral"><span>Domestic Optimum</span><strong>2.5%</strong><small>205 bookings for 200 seats</small></div><div className="retail-metric-card retail-metric-card--slate"><span>International Optimum</span><strong>6.25%</strong><small>425 bookings for 400 seats</small></div><div className="retail-metric-card retail-metric-card--sage"><span>Domestic Revenue</span><strong>$62,564.67</strong><small>Maximum modeled revenue per flight</small></div><div className="retail-metric-card"><span>Industry Validation</span><strong>~$7 / passenger</strong><small>Model landed within about $1</small></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Modeling &amp; Decision Design</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>Modeling the true cost of a bump</h3><p>Combined short-term compensation with a Customer Lifetime Value estimate and a logistic loyalty-loss curve tied to delay time. The result was a blended cost per bumped passenger rather than a single payout assumption.</p><div className="retail-callout"><strong>Modeled compensation</strong><p>$1,802.52 domestic and $5,936.91 international per bumped passenger, based on separate flight assumptions.</p></div></article><article className="retail-dashboard-card"><h3>Optimizing under uncertainty</h3><p>Used a binomial no-show model and Monte Carlo trials to sweep booking levels, estimate net revenue, and identify the point where additional bookings no longer outweighed bumping costs.</p><div className="retail-callout retail-callout--sage"><strong>Decision output</strong><p>The optimum stays below the expected no-show rate because aggressive overbooking increases compensation and loyalty risk.</p></div></article></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Sensitivity &amp; Validation</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>Situational overbooking, not one fixed rule</h3><p>Ran a two-dimensional sensitivity analysis across no-show rate and compensation to show how the recommended rate changes by flight conditions, route type, and risk tolerance.</p><div className="retail-callout"><strong>Practical conclusion</strong><p>The report recommends adjusting overbooking by situation instead of applying one universal percentage.</p></div></article><article className="retail-dashboard-card"><h3>Validated against airline economics</h3><p>The full compensation → revenue → profit pipeline produced modeled profit-per-passenger figures close to the cited industry average without tuning the model to hit the benchmark.</p><div className="retail-callout retail-callout--sage"><strong>Benchmark check</strong><p>$7.14 domestic and $6.21 international landed within roughly $0.86–$1.00 of the ~$7 industry reference.</p></div></article></div></section>

        <section className="retail-dashboard-section airline-evidence-section"><h2 className="retail-dashboard-section-title">Revenue Optimization Evidence</h2><p className="airline-evidence-note">The modeled revenue curve peaks at 205 passengers for a 200-seat domestic flight before compensation costs dominate.</p><div className="airline-visual"><img src="../airline-overbooking-revenue.svg" alt="Revenue optimization curve showing a peak at 205 passengers for a 200-seat flight" /></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Technology</h2><div className="retail-tech-stack"><TagList items={['Python', 'NumPy', 'Pandas', 'Matplotlib', 'Seaborn', 'Jupyter', 'Monte Carlo', 'Probability Modeling']} /></div><p className="retail-private-note">A completed two-person research project using literature-derived airline assumptions, standalone Python analysis modules, notebooks, and a written report.</p></section>
      </main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><span className="footer-year">© 2026</span></footer>
    </div>
  )
}

function DataAnalysisEdaPage() {
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell eda-page">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><a className="back-link" href={backHref}>&larr; Back to portfolio</a></header>
      <main className="retail-dashboard section-wrap eda-dashboard">
        <header className="retail-dashboard-header"><div className="retail-dashboard-title"><div><h1>Exploratory Data Analysis</h1><p>Two completed Python notebook analyses that apply the same disciplined workflow to different domains: retail transactions and Premier League match data.</p></div><a className="eda-repo-button" href="https://github.com/ZachSkiba/Data-Analysis-Projects" target="_blank" rel="noreferrer">View on GitHub <Icon name="arrow" size={16} /></a></div><div className="retail-badge-container"><span className="retail-badge retail-badge-status"><i /> Completed analyses</span><span className="retail-badge">Python notebooks</span><span className="retail-badge">Retail + sports</span><span className="retail-badge">Solo projects</span></div></header>

        <section className="retail-metrics-grid" aria-label="Project metrics"><div className="retail-metric-card retail-metric-card--coral"><span>Superstore scale</span><strong>9,800</strong><small>Retail orders across four years</small></div><div className="retail-metric-card retail-metric-card--slate"><span>Premier League scale</span><strong>380</strong><small>Matches from the full 2022-23 season</small></div><div className="retail-metric-card retail-metric-card--sage"><span>Retention finding</span><strong>99.2%</strong><small>Customers were repeat buyers</small></div><div className="retail-metric-card"><span>Home advantage</span><strong>48.42%</strong><small>Home win rate across the season</small></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Two datasets, one analytical workflow</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>Superstore Sales EDA</h3><p>Cleaned and analyzed 9,800 retail transactions across product, customer, shipping, regional, time, and retention dimensions.</p><div className="retail-callout"><strong>Key finding</strong><p>Product order volume and revenue had only a weak relationship (r = 0.14), while 99.2% of customers made repeat purchases.</p></div></article><article className="retail-dashboard-card"><h3>Premier League EDA</h3><p>Analyzed match-level outcomes across 380 games, then aggregated the data to the team-season level to compare shots and goals with final league rank.</p><div className="retail-callout retail-callout--sage"><strong>Key finding</strong><p>Home teams won 48.42% of matches and scored 57.29% of all goals; the rank analysis is a secondary finding based on 20 clubs.</p></div></article></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Technical approach</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>Data preparation</h3><p>Validated nulls, duplicates, types, and ranges before analysis. Standardized fields, parsed dates, and removed identifiers that could mask duplicate retail transactions.</p><div className="retail-callout"><strong>Reliable inputs</strong><p>Both notebooks move from checked source data into documented summaries and visual evidence.</p></div></article><article className="retail-dashboard-card"><h3>Analysis design</h3><p>Used groupby summaries for products, customers, teams, and seasons, matching the unit of analysis to the question instead of forcing one table to answer everything.</p><div className="retail-callout retail-callout--sage"><strong>Clear communication</strong><p>Each notebook pairs charts with short written interpretations so the findings are easy to follow.</p></div></article></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Technology</h2><div className="retail-tech-stack"><TagList items={['Python', 'pandas', 'NumPy', 'Matplotlib', 'Seaborn', 'Jupyter']} /></div><p className="retail-private-note">These are completed descriptive and correlational analyses, not predictive models. The Premier League team-season correlation uses 20 clubs and is presented as a secondary finding.</p></section>
      </main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><span className="footer-year">&#169; 2026</span></footer>
    </div>
  )
}

function TriXpensePage() {
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell trixpense-page">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><a className="back-link" href={backHref}>← Back to portfolio</a></header>
      <main className="trixpense-recruiter section-wrap">
        <header className="trixpense-recruiter-header"><div className="trixpense-recruiter-title"><div><h1>TriXpense</h1><p>A live full-stack expense management application for tracking shared bills, clarifying balances, and helping people manage money together.</p></div><a className="trixpense-live-button" href="https://trixpense.com" target="_blank" rel="noreferrer">Open live app <Icon name="arrow" size={16} /></a></div><div className="trixpense-badges"><span className="trixpense-badge trixpense-badge--live"><i /> Live product</span><span className="trixpense-badge">Production application</span><span className="trixpense-badge">No public repository</span></div></header>

        <section className="trixpense-metrics" aria-label="Product overview"><div><span>Product type</span><strong>Full-stack web app</strong><small>Built for personal and shared finance workflows</small></div><div><span>Primary workflow</span><strong>Expense → balance → settlement</strong><small>Turns scattered transactions into an understandable next step</small></div><div><span>Core users</span><strong>Individuals &amp; groups</strong><small>Personal trackers and shared group trackers</small></div><div><span>Public proof</span><strong>Live at trixpense.com</strong><small>Code is private; the product is available to explore</small></div></section>

        <section className="trixpense-recruiter-section"><h2 className="trixpense-recruiter-section-title">Product evidence</h2><p className="trixpense-evidence-note">Primary interface: the signed-in dashboard brings the tracker, filters, current balances, and suggested settlements into one operational view.</p><div className="trixpense-recruiter-dashboard"><img src="../trixpense-dashboard.webp" alt="TriXpense group tracker dashboard showing transactions, filters, current balances, and suggested settlements" /></div></section>

        <section className="trixpense-recruiter-section"><h2 className="trixpense-recruiter-section-title">System scope</h2><div className="trixpense-scope-grid"><div><span>Core product capabilities</span><ul><li>Shared group tracker and advanced filters</li><li>Suggested settlements and monthly summaries</li><li>Budgeting tables and visual analytics</li><li>Recurring payments and notifications</li><li>PDF/CSV export and subscription flows</li></ul></div><div><span>Technical implementation</span><ul><li>Flask application with server-rendered interfaces</li><li>PostgreSQL data model through SQLAlchemy</li><li>Authentication, account management, and access control</li><li>Receipt pipeline: OCR → parsing → categorization</li><li>Async processing with Gemini Vision and Tesseract fallback</li></ul></div></div></section>

        <section className="trixpense-recruiter-section trixpense-tech-section"><h2 className="trixpense-recruiter-section-title">Technology</h2><TagList items={['Python', 'Flask', 'PostgreSQL', 'SQLAlchemy', 'JavaScript', 'Stripe', 'OCR', 'Gemini Vision', 'Tesseract', 'OpenCV']} /><p className="trixpense-private-note">The codebase is private. The live application is available for product review.</p></section>
      </main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><span className="footer-year">© 2026</span></footer>
    </div>
  )
}

function RetailForecastPage() {
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell retail-page">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><a className="back-link" href={backHref}>← Back to portfolio</a></header>
      <main className="retail-dashboard section-wrap">
        <header className="retail-dashboard-header">
          <div className="retail-dashboard-title"><div><h1>Retail Demand Intelligence System</h1><p>An end-to-end time series forecasting &amp; decision-support pipeline progressing from classical statistical baselines (SARIMA, Prophet) to global gradient-boosted models (LightGBM Tweedie) across 58M+ sales records.</p></div><span className="retail-phase">Phase 1–2 complete<br /><b>Phase 3 in progress</b></span></div>
          <div className="retail-badge-container"><span className="retail-badge retail-badge-status"><i /> In Progress (Phase 1 Complete)</span><span className="retail-badge">M5 Walmart Dataset</span><span className="retail-badge">30,490 Series</span><span className="retail-badge">Fold 3 Reserved</span></div>
        </header>

        <section className="retail-metrics-grid" aria-label="Project metrics"><div className="retail-metric-card retail-metric-card--coral"><span>Leading ML Model</span><strong>3.10 RMSE</strong><small>LightGBM Tweedie (~7.8% WAPE)</small></div><div className="retail-metric-card retail-metric-card--slate"><span>Data Scale</span><strong>58.3M Rows</strong><small>30,490 Product-Store Series</small></div><div className="retail-metric-card retail-metric-card--sage"><span>Zero Inflation</span><strong>68.2%</strong><small>Handled via Gap-Aware Features</small></div><div className="retail-metric-card"><span>Validation Discipline</span><strong>3-Fold Walk</strong><small>Fold 3 Untouched Final Holdout</small></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Engineering Breakthroughs &amp; Diagnostics</h2><div className="retail-breakthrough-grid"><article className="retail-dashboard-card"><h3>1. The &quot;Signal Ceiling&quot; Discovery</h3><p>Before building heavy ML models, classical baselines (SARIMA &amp; Prophet) were tuned independently. Both models hit an identical performance floor—failing on the exact same 3 months (Apr 2015, May 2015, Jan 2016).</p><div className="retail-callout"><strong>Engineering Takeaway</strong><p>Proved univariate models lacked sufficient context. Feature engineering was explicitly built to target these gaps using SNAP cycles and multi-level price elasticity.</p></div></article><article className="retail-dashboard-card"><h3>2. Rejecting Metric-Winning Calibration</h3><p>Global isotonic calibration improved log-RMSE and mean bias significantly in aggregate. However, a deeper per-SKU distribution audit revealed it badly overcorrected individual sparse series (2–8× actual demand).</p><div className="retail-callout retail-callout--sage"><strong>Operational Rigor</strong><p>Chose to reject the aggregate &quot;win&quot; in favor of Syntetos-Boylan demand-regime routing (routing lumpy SKUs to Croston/TSB models).</p></div></article></div></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Model Benchmark Matrix (Fold 2 Diagnostics)</h2><div className="retail-table-wrap"><table className="retail-table"><thead><tr><th>Model Family</th><th>Objective / Approach</th><th>Aggregate Metric</th><th>Representative Series</th><th>Key Assessment</th></tr></thead><tbody><tr><td><strong>Naive Baseline</strong></td><td>Previous Period Carry-over</td><td>—</td><td>55.29% MAPE</td><td>Unusable benchmark</td></tr><tr><td><strong>SARIMA</strong></td><td>(2,0,1)(0,1,1)[12] Classical</td><td>6.91% MAPE</td><td>22.22% MAPE</td><td>Hits univariate signal ceiling</td></tr><tr><td><strong>Prophet</strong></td><td>Multiplicative Seasonality</td><td>5.02% MAPE</td><td>24.25% MAPE</td><td>Struggles with local demand shifts</td></tr><tr><td><strong>XGBoost v2</strong></td><td>log1p Target (39 Features)</td><td>3.39 Unit RMSE</td><td>—</td><td>Retransformation underprediction bias</td></tr><tr className="retail-table-highlight"><td><strong>LightGBM (Winner)</strong></td><td>Native Tweedie Objective</td><td><strong>3.10 Unit RMSE (~7.8% WAPE)</strong></td><td><strong>Closed Ceiling Gaps</strong></td><td><strong>Leading Candidate (Native unit space)</strong></td></tr></tbody></table></div><p className="retail-table-note">Metrics come from different evaluation tiers and are shown as interim diagnostics. Final Fold 3 production performance has not been established.</p></section>

        <section className="retail-dashboard-section"><h2 className="retail-dashboard-section-title">Project Roadmap &amp; Execution Plan</h2><div className="retail-roadmap retail-dashboard-card"><div className="retail-roadmap-item retail-roadmap-item--complete"><i /><div><h3>Phase 1: EDA &amp; Statistical Baseline Diagnosis</h3><p>Quantified 68.2% zero inflation, price elasticity at 3 granularities, and confirmed the SARIMA/Prophet signal ceiling.</p></div></div><div className="retail-roadmap-item retail-roadmap-item--complete"><i /><div><h3>Phase 2: Gap-Aware Feature Engineering &amp; Tree Models</h3><p>Iterated feature set from 34 to 39 features (28-day gap nulling logic); confirmed LightGBM Tweedie outperformance.</p></div></div><div className="retail-roadmap-item retail-roadmap-item--active"><i /><div><h3>Phase 3: Demand-Regime Routing &amp; Uncertainty (Current)</h3><p>Categorizing SKUs via Syntetos-Boylan (ADI/CV²) classification; adding Conformal Prediction for calibrated safety stock bands.</p></div></div><div className="retail-roadmap-item"><i /><div><h3>Phase 4: Inventory Backtest &amp; One-Time Fold 3 Evaluation</h3><p>Simulating reorder point/safety stock outcomes, followed by the single, untouched evaluation on Fold 3.</p></div></div><div className="retail-roadmap-item"><i /><div><h3>Phase 5: Interactive Streamlit Decision-Support App</h3><p>Surfacing inventory risk, SHAP explainability, and backtest results in a fast 5-page dashboard consuming Parquet predictions.</p></div></div></div></section>

        <section className="retail-dashboard-section retail-tech-section"><h2 className="retail-dashboard-section-title">Technology</h2><div className="retail-tech-stack"><TagList items={['Python', 'pandas', 'NumPy', 'statsmodels', 'Prophet', 'scikit-learn', 'XGBoost', 'LightGBM', 'Optuna']} /></div><p className="retail-private-note">This project is actively in development and is not currently shared publicly.</p></section>
      </main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}>Zach Skiba</a><span className="footer-year">© 2026</span></footer>
    </div>
  )
}

export default function DetailPage({ slug }: { slug: string }) {
  if (slug === 'retail-demand-forecasting') return <RetailForecastPage />
  if (slug === 'roommate-expense-tracker') return <TriXpensePage />
  if (slug === 'diabetes-prediction') return <DiabetesClassificationPage />
  if (slug === 'ab-test-efficiency') return <ABTestEfficiencyPage />
  if (slug === 'airline-overbooking') return <AirlineOverbookingPage />
  if (slug === 'data-analysis-eda') return <DataAnalysisEdaPage />
  const data = details[slug] ?? details['retail-demand-forecasting']
  const backHref = '../index.html'
  return (
    <div className="site-shell detail-shell">
      <header className="detail-header section-wrap"><a className="footer-name" href={backHref}><span className="identity-mark">Z</span><span>Zach</span></a><a className="back-link" href={backHref}>← Back to portfolio</a></header>
      <main className="detail-main section-wrap"><p className="section-kicker">{data.type} / {data.eyebrow}</p><div className="detail-heading"><h1>{data.title}</h1><span>{data.meta}</span></div><TagList items={data.tags} className="detail-tags" />{data.image && <img className="detail-image" src={data.image} alt="Project placeholder" />}<div className="detail-body"><p className="detail-lede">{data.description}</p><div><h2>Overview</h2><p>[PLACEHOLDER: describe the problem, context, and why this work mattered.]</p><p>[PLACEHOLDER: describe your approach, your role, and the tools or methods you used.]</p><p>[PLACEHOLDER: describe the result, what you learned, and what you would improve next.]</p></div></div><div className="detail-actions"><a className="read-more" href={backHref}>← Back to portfolio</a><a className="detail-repo" href="#contact">{data.repoLabel} <Icon name="arrow" size={15} /></a></div></main>
      <footer className="site-footer section-wrap"><a className="footer-name" href={backHref}><span className="identity-mark">Z</span><span>Zach</span></a><span className="footer-year">© 2026</span></footer>
    </div>
  )
}
